print()
print("="* 20, "ASSIGNMENT # 1", "=" *20)
print("-" * 13, "coded by Nathaniel Finuliar", "-" *14)
print("=" * 22, "BSCOE 2-2", "=" * 23) 
print()
print()
print("*" *6,"*")
print("*" *6,"*"*3)
print("*" *6,"**"*4)
print("*" *6,"**")
print("*" *6)
print("*" *6)
print("*" *6)

