print()
print("="* 20, "ASSIGNMENT # 1", "=" *20)
print("-" * 13, "coded by Nathaniel Finuliar", "-" *14)
print("=" * 22, "BSCOE 2-2", "=" * 23) 
print()
print()
print("*" *3)
print("*" *3,"*"*1)
print("*" *3,"*"*3)
print("*" *3,"*"*4)
print("*" *3,"*"*4)
print("*" *3,"*"*5)
print("*" *3," "*5)

